spark:
  jars:
    # 当前 JAR 的名字，支持相对路径，如果使用匿名内部类，会生成$1的class，不添加jar，会出现ClassNotFoundException
    - target/cdh-demo-0.0.1-SNAPSHOT.jar
  app-name: cdh-demo
  master-url: spark://cdh-slave-1:7077
  driver:
    memory: 1g
    host: 10.8.0.5
    # JDBC 驱动地址,手动上传到 hdfs 的
    extraClassPath: hdfs://cdh-slave-1:8020/jars/mysql-connector-java-5.1.47.jar
  worker:
    memory: 1g
  executor:
    memory: 1g
  rpc:
    message:
      maxSize: 1024
  streaming:
    kafka:
      topics:
        - spark-streaming-demo
logging:
  level:
    org:
      apache:
        spark:
          storage: WARN
          deploy:
            client: WARN
          scheduler:
            cluster: WARN
hadoop:
  url: hdfs://cdh-slave-1:8020
  replication: 3
  blockSize: 2097152
  user: root
spring:
  kafka:
    bootstrap-servers: cdh-slave-2:9092
    producer:
      acks: 1
      retries: 10
      # 32mb
      buffer-memory: 33554432
      # 1mb
      batch-size: 1048576
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      # 默认topic
      default-topic: spark-streaming
    consumer:
      group-id: my-group  # 指定消费者组 ID，如果不指定，会随机生产新的
      auto-offset-reset: earliest  # 指定从哪里开始消费，可选值为 earliest 或 latest
      max-poll-records: 500  # 最大拉取的消息数量
      enable-auto-commit: false  # 是否自动提交消费位移
      max-poll-interval-ms: 30000  # 每次拉取消息的最大时间间隔
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # 指定 key 的反序列化器
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # 指定 value 的反序列化器
